hmcts/pre-api

config/owasp/suppressions.xml
Added owasp suppression for jackson-databind (CVE-2023-35116)
=> fix: add owasp suppression for jackson-databind

charts/pre-api/Chart.yaml, charts/pre-api/values.yaml
use sds acr
use cluster internal url for now
```
[ ] Yes
[x] No
```
=> Change acr location, use internal url for now

charts/pre-api/Chart.yaml, charts/pre-api/values.yaml
=> update port in chart

Jenkinsfile_CNP
=> Add branch sync and slack build notifications

.github/renovate.json
=> Add security label and rebase when behind master

charts/pre-api/Chart.yaml, charts/pre-api/values.yaml
=> Corrects KV value names

Jenkinsfile_CNP
=> use debugging jenkins lib branch

build.gradle, src/main/resources/application.yaml
=> Remove unused dep and fix springdoc config for API spec generation

config/owasp/suppressions.xml
=> Three OWASP suppressions

src/main/java/uk/gov/hmcts/reform/preapi/controllers/BookingController.java, src/main/java/uk/gov/hmcts/reform/preapi/enums/UpsertResult.java, src/main/java/uk/gov/hmcts/reform/preapi/exception/GlobalControllerExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/preapi/exception/UnknownServerException.java, src/main/java/uk/gov/hmcts/reform/preapi/model/Participant.java, src/main/java/uk/gov/hmcts/reform/preapi/services/BookingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/BookingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java
=> Upsert booking in db

src/main/java/uk/gov/hmcts/reform/preapi/controllers/RecordingController.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/CaptureSession.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Recording.java, src/main/java/uk/gov/hmcts/reform/preapi/model/Recording.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/RecordingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/RecordingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/RecordingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/model/RecordingTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2239
- Add GET `/bookings/{bookingId}/recordings/{recordingId}`
- Add recording model
```
[ ] Yes
[x] No
```
=> S28-2239: API `GET /bookings/{bookingId}/recordings/{recordingId}`

src/main/java/uk/gov/hmcts/reform/preapi/controllers/RecordingController.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/RecordingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/RecordingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/RecordingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2240
- Add new GET endpoint: `/bookings/{bookingId}/recordings`
```
[ ] Yes
[x] No
```
=> S28 2240: GET `/bookings/{bookingId}/recordings`

build.gradle, src/main/java/uk/gov/hmcts/reform/preapi/controllers/BookingController.java, src/main/java/uk/gov/hmcts/reform/preapi/model/Booking.java, src/main/java/uk/gov/hmcts/reform/preapi/model/Participant.java, src/main/java/uk/gov/hmcts/reform/preapi/services/BookingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/BookingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/model/ParticipantTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java
=> S28 2225/get booking by

build.gradle
=> Revert flyway plugin update

src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/RecordingController.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/RecordingDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/services/RecordingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/RecordingControllerTest.java
=> RecordingDTO added

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/S28-2272
fixing nightly pipeline setup issue
```
[ ] Yes
[x] No
```
=> fixing nightly pipeline to pre api

config/checkstyle/checkstyle.xml, src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/AppAccessTest.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/CaptureSessionTest.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/CaseDTOTest.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/CourtTest.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/CreateBookingDTOTest.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/CreateParticipantDTOTest.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/CreateRecordingDTOTest.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/PortalAccessTest.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/ShareRecordingTestDTO.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/UserTest.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/BookingServiceIT.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/util/HelperFactory.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/BookingController.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/BookingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/BookingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/BookingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java
=> Search for Bookings by caseId or ref

src/main/java/uk/gov/hmcts/reform/preapi/controllers/BookingController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/CaseController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/CourtController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/RecordingController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/UserController.java
Adds additional meta data to the API documentation so that the component generated for Power Apps has more sensibly named functions.
```
[ ] Yes
[x] No
```
=> Adds meta data to API docs

src/main/java/uk/gov/hmcts/reform/preapi/services/BookingService.java, src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java
- Gets booking entity when updating
- Gets participant entity when updating
- Saves participant entity when creating/updating
```
[ ] Yes
[x] No
```
=> Fix: Save participant when created/updated and set court

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/BookingServiceIT.java, src/main/java/uk/gov/hmcts/reform/preapi/config/WebConfiguration.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/BookingController.java, src/main/java/uk/gov/hmcts/reform/preapi/exception/GlobalControllerExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/preapi/exception/RequestedPageOutOfRangeException.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/BookingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/BookingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/BookingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java
=> Paginated, sortable bookings for case

src/main/java/uk/gov/hmcts/reform/preapi/controllers/UserController.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/AppAccessRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/PortalAccessRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/UserRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/UserService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/UserControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/UserServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2267
- Add endpoint DELETE `/users/{id}`
```
[ ] Yes
[x] No
```
=> S28 2267: DELETE `/users/{id}`

src/main/java/uk/gov/hmcts/reform/preapi/controllers/RecordingController.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/RecordingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/CaseService.java, src/main/java/uk/gov/hmcts/reform/preapi/services/CourtService.java, src/main/java/uk/gov/hmcts/reform/preapi/services/RecordingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/RecordingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/CaseServiceTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/CourtServiceTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceTest.java
=> Fix: API PUT Errors + General Code Cleanup

build.gradle
Updated flyway postgres host for flyway gradle tasks in `build.gradle` so automatically works with locally running postgres instance. 
=> Fix flyway postgres host for gradle tasks

pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/dto/UserDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/base/BaseUserDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/services/UserService.java
- Add active boolean to `GET /users` and `GET /users/{id}` response
- Add active boolean to `PUT /users/{id}` request body
```
[ ] Yes
[x] No
```
=> Fix: Add `active` UserDTO and CreateUserDTO

src/main/java/uk/gov/hmcts/reform/preapi/services/BookingService.java, src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java
- In upsert booking function, find expected case by id if not throw not found exception
```
[ ] Yes
[x] No
```
=> Fix: Case Not Saved Booking Error

build.gradle, src/main/java/uk/gov/hmcts/reform/preapi/entities/Audit.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/CaptureSession.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Court.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Participant.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/PortalAccess.java
=> Uddate Springboot and Flyway

pre-api-stg.yaml, src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/CaseControllerFT.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/TestingSupportController.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/CaseDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/CreateCaseDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Case.java, src/main/java/uk/gov/hmcts/reform/preapi/services/CaseService.java, src/test/java/uk/gov/hmcts/reform/preapi/services/CaseServiceTest.java
=> Adds ability to create participants during Case creation

pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/controllers/ReportController.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/reports/SharedReportDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/ShareBooking.java, src/main/java/uk/gov/hmcts/reform/preapi/services/ReportService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/ReportControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/ReportServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2368
- Add endpoint `GET /reports/shared-bookings` to replace `v_recordings_shared_report`
```
[ ] Yes
[x] No
```
=> S28 2368: API Report Bookings Shared

pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/controllers/RoleController.java, src/main/java/uk/gov/hmcts/reform/preapi/services/RoleService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/RoleControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/RoleServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2370
- Add endpoint `GET /roles`
```
[ ] Yes
[x] No
```
=> S28 2370: API GET `/roles`

pre-api-stg.yaml, src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/AuditTest.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/ReportController.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/reports/PlaybackReportDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Audit.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/AuditRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/ReportService.java, src/main/resources/db/migration/V007__AuditCreatedByToUuid.sql, src/test/java/uk/gov/hmcts/reform/preapi/services/ReportServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2369
- Add endpoint `GET /reports/playback?source=PORTAL` to replace `v_portal_playback_report`
- Add endpoint `GET /reports/playback?source=APPLICATION` to replace `v_application_playback_report`
```
[ ] Yes
[x] No
```
=> S28 2369: API Report Playback (Portal/Application)

pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/dto/BookingDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/CaptureSessionDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/CreateCaptureSessionDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/CreateRecordingDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/RecordingDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/base/BaseRecordingDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Booking.java, src/test/java/uk/gov/hmcts/reform/preapi/dto/CaptureSessionDTOTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceTest.java
The Recording.captureSessionId value has moved to Recording.captureSession.id
```
[x] Yes
[ ] No
```
=> Return capture session for booking and recording

charts/pre-api/Chart.yaml, charts/pre-api/values.yaml
new vaults have been created to match prod naming convention.
```
[ ] Yes
[x] No
```
=> S28-2314 Update Key Vault Name

pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/dto/base/BaseRecordingDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/reports/CaptureSessionReportDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/reports/PlaybackReportDTO.java
=> Return Duration as a string for report

lib/applicationinsights.json, src/main/resources/application.yaml
=> Update Secrets mnt path for new KV

charts/pre-api/Chart.yaml, charts/pre-api/values.dev.template.yaml, charts/pre-api/values.stg.template.yaml, charts/pre-api/values.yaml, pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/controllers/TestingSupportController.java, src/main/resources/application.yaml, src/smokeTest/java/uk/gov/hmcts/reform/preapi/controllers/SmokeTest.java, src/smokeTest/resources/application.properties
=> Smoke test for APIm working with authentication enabled

src/functionalTest/java/uk/gov/hmcts/reform/preapi/util/FunctionalTestBase.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/TestingSupportController.java
- Add clean-up call to clear the db before each functional test
- Fix case reference conflict error in functional test (caused by db not being cleaned up between tests)
```
[ ] Yes
[x] No
```
=> Fix: Functional Test Clean up

src/main/java/uk/gov/hmcts/reform/preapi/controllers/TestingSupportController.java
- Add flush() after deleteAll() on each repository
```
[ ] Yes
[x] No
```
=> Fix: FT Flush After Clean Up

src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/CaseControllerFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/util/FunctionalTestBase.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/TestingSupportController.java
- Add function that randomly generates case reference to FT
```
[ ] Yes
[x] No
```
=> Fix: FT Generate Random Case Reference

README.md
=> README description and LLD

src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/TestingSupportController.java
=> FT for deleting non-existant booking

src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/TestingSupportController.java
=> FT covers rooms and regions being returned by bookings

pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/dto/CreateBookingDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/validators/ParticipantTypeConstraint.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/validators/ParticipantTypeValidator.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/BookingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/util/HelperFactory.java
=> Require at least 1 participant in a Booking

src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/RecordingController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/TestingSupportController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchBookings.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchRecordings.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/BookingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/CaseRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/RecordingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/BookingService.java, src/main/java/uk/gov/hmcts/reform/preapi/services/RecordingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/RecordingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2240
- Fix `GET /bookings` search param `scheduledFor`
- Add search params for `GET /recordings`
- `caseReference`
- `schuduledFor`
```
[ ] Yes
[x] No
```
=> S28 2240: `GET /recordings` New Search Params + Fix Bookings `scheduledFor` Search Param

src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/CaseServiceIT.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/BookingDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/CaseDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/services/CaseService.java
- Fix error when removing participant from a case
- Hide deleted participants in CaseDTO and BookingDTO
```
[ ] Yes
[x] No
```
=> Fix: Participant Deletion when Updating Cases

pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/config/OpenAPIConfiguration.java
=> Add Swagger docs for X-User-Id header

pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/config/OpenAPIConfiguration.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/BookingController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/CaptureSessionController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/CaseController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/CourtController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/InviteController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/RecordingController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/UserController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchCaptureSessions.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/CaptureSessionRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/CaptureSessionControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2403
- Add endpoint `GET /capture-sessions`
- Changed example `page` parameter value to 0
```
[ ] Yes
[x] No
```
=> S28 2403: API GET `/capture-sessions`

Jenkinsfile_CNP
=> Don't sync to ITHC whilst the env isn't there

pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/controllers/BookingController.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/ShareBooking.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/ShareBookingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/BookingService.java, src/main/java/uk/gov/hmcts/reform/preapi/services/ShareBookingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/BookingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/ShareBookingServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2379
- Add `DELETE /bookings/{bookingId}/share/{shareId}`
- Add share bookings to delete cascade (shares are deleted when related booking is deleted). 
```
[ ] Yes
[x] No
```
=> S28 2379: API DELETE `/bookings/{bookingId}/share/{shareId}` + Delete Cascade

src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/AuditTest.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/RoleDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Audit.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Recording.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Role.java
- Align entities with new migrations
```
[ ] Yes
[x] No
```
=> 2188: JPA Entity Aligned to New Migrations

Jenkinsfile_CNP
=> Update KV name used for db migrations

build.gradle, pre-api-stg.yaml, src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/AuditTest.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/reports/ConcurrentCaptureSessionReportDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/AppAccess.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Booking.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/CaptureSession.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Case.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Court.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Invite.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Participant.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Permission.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/PortalAccess.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Recording.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/Role.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/ShareBooking.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/User.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/base/BaseEntity.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/listeners/AuditListener.java
=> AuditDetails for each entity

pre-api-stg.yaml, src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/BookingServiceIT.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/BookingController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchBookings.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/BookingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/BookingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/BookingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java
=> Search Bookings by Court Id

pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/dto/ShareBookingDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/base/BaseUserDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/services/ShareBookingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/BookingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/dto/ShareBookingDTOTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/ShareBookingServiceTest.java, src/test/java/uk/gov/hmcts/reform/preapi/util/HelperFactory.java
=> Include BaseUserDTO in SharedBookingDTO

pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/dto/RecordingDTO.java, src/test/java/uk/gov/hmcts/reform/preapi/dto/RecordingDTOTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceTest.java, src/test/java/uk/gov/hmcts/reform/preapi/util/HelperFactory.java
=> Adds CaseRef and Participants to RecordingDTO

infrastructure/main.tf, pre-api-stg.yaml, src/functionalTest/java/uk/gov/hmcts/reform/preapi/security/XUserIdFilterFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/util/FunctionalTestBase.java, src/main/java/uk/gov/hmcts/reform/preapi/config/OpenAPIConfiguration.java, src/main/java/uk/gov/hmcts/reform/preapi/config/SecurityConfig.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/AuditController.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/listeners/AuditListener.java, src/main/java/uk/gov/hmcts/reform/preapi/security/filter/XUserIdFilter.java, src/main/java/uk/gov/hmcts/reform/preapi/services/AuditService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/AuditControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/security/XUserIdFilterTest.java
=> Remove auth from audit and make x-user-id optional

infrastructure/main.tf, src/main/java/uk/gov/hmcts/reform/preapi/config/SecurityConfig.java
- Disbaled CSRF
```
[ ] Yes
[x] No
```
=> Fix: Disable CSRF

.github/workflows/publish-swagger-v2-and-bump-apim-revision.yaml
=> Only increment APIM revision if changes made to the api

infrastructure/main.tf, pre-api-stg.yaml, src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/UserServiceIT.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/UserController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchUsers.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/PortalAccessDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/base/BaseUserDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/User.java, src/main/java/uk/gov/hmcts/reform/preapi/enums/AccessType.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/AppAccessRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/UserRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/UserService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/UserControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/UserServiceTest.java
=> S28 2424/users by access

bin/migration/tables/portalaccess.py, pre-api-stg.yaml, src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/PortalAccessTest.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/PortalAccessDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/PortalAccess.java, src/main/resources/db/migration/V013__ConsistentPortalAccessColumns.sql
=> Make PortalAccess column names consistent with other tables

pre-api-stg.yaml, src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/BookingController.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/CreateShareBookingDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/ShareBookingDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/ShareBookingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/security/AuthorisationService.java, src/main/java/uk/gov/hmcts/reform/preapi/services/ShareBookingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/BookingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/dto/CreateShareBookingDTOTest.java, src/test/java/uk/gov/hmcts/reform/preapi/security/AuthorisationServiceTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/ShareBookingServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2439
- Add endpoint `GET /bookings/{id}/share`
```
[ ] Yes
[x] No
```
=> S28 2439: Add Endpoint GET `/bookings/{id}/share`

src/main/java/uk/gov/hmcts/reform/preapi/services/RecordingService.java, src/test/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceTest.java
- Fix error caused by trying to create a recording without a capture session
```
[ ] Yes
[x] No
```
=> Fix: PUT `/recording/{id}` Capture Session Error 

src/main/java/uk/gov/hmcts/reform/preapi/repositories/BookingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/ShareBookingService.java, src/test/java/uk/gov/hmcts/reform/preapi/services/ShareBookingServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2439
- Fix 404 error when getting share logs for booking that exists
- Fix 404 error when deleting share for booking that exists
```
[ ] Yes
[x] No
```
=> Fix: Remove 404 Error when Booking Exists

infrastructure/main.tf
=> Deploy infra to prod

pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/controllers/RecordingController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchRecordings.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/RecordingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/RecordingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/RecordingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2468
- Add search param `participantName` for `/recordings`
```
[ ] Yes
[x] No
```
=> S28 2468: Search Recordings by Participant Name

bin/migration/tables/participants.py
- [ X] commit messages are meaningful and follow good commit message guidelines
- [ X] README and other documentation has been updated / added (if needed)
- [ X] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/S28-2412 
adding in deleted_at field for inactive participants
```
[ ] Yes
[X ] No
```
=> adding in deleted_at field for inactive participants

pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/controllers/RecordingController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchRecordings.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/RecordingRepository.java
https://tools.hmcts.net/jira/browse/S28-2468
- Remove search param `participantName`
- Add search params `witnessName` and `defendantName`
```
[ ] Yes
[x] No
```
=> S28 2468: Recording Search Params Update (`witnessName`, `defendantName`)

src/main/resources/db/migration/V015__UpdateFieldLength.sql
- [ X] commit messages are meaningful and follow good commit message guidelines
- [X ] README and other documentation has been updated / added (if needed)
- [X ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/S28-2466
Increase audit activity field to 255 chars
```
[ ] Yes
[X ] No
```
=> increase audit activity field as too short

.github/workflows/publish-swagger-v2-and-bump-apim-revision.yaml
=> Amend action to compare branch to master

infrastructure/main.tf
=> Fix: Bump APIm Version to 33

src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceIT.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/TestingSupportController.java, src/main/resources/db/migration/V017__AddUniqueConstraints.sql
https://tools.hmcts.net/jira/browse/S28-2393
- Added unique constraints to various column / column combos where appropriate to avoid duplicate data being entered in to the database. This will also speed up queries by creating new indexes.
- Updated the recording service integration test to avoid duplicate recording version being inserted, triggering the new constraint.
=> S28-2393 Add unique constraints to appropriate columns

pre-api-stg.yaml, src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/BookingServiceIT.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/BookingController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchBookings.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/BookingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/BookingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/BookingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java
- Add search param `captureSessionStatus` to `GET /bookings` 
```
[ ] Yes
[x] No
```
=> Feature: Add search param `captureSessionStatus` to `GET /bookings`

infrastructure/main.tf, pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/controllers/UserController.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/AppAccessDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/UserDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/services/UserService.java, src/test/java/uk/gov/hmcts/reform/preapi/services/UserServiceTest.java
- Change GET /users/{id} to search users table for id instead of app access table
```
[ ] Yes
[x] No
```
=> Fix: `GET /users/{id}` Should Return Users without App Access 

infrastructure/main.tf, pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/dto/RecordingDTO.java
=> Return case isTest flag with recordings

bin/migration/main_script.py, bin/migration/migration_reports/failed_imports_logger.py, bin/migration/migration_reports/migration_tracker.py, bin/migration/tables/bookings.py, bin/migration/tables/capturesessions.py, bin/migration/tables/helpers.py, bin/migration/tables/participants.py, bin/migration/tables/recordings.py, bin/migration/tables/sharebookings.py, infrastructure/main.tf
- [X ] commit messages are meaningful and follow good commit message guidelines
- [ X] tests have been updated / new tests has been added (if needed)
Changes made to capture_sessions, recordings and share bookings that were captured in another PR which was conflicting with another.
This PR resolves the problem with running the script multiple times. With the added changes, we are now looping through the failed migration file, save the current items into a cache, and before inserting any new records, check for duplications within the cache.
```
[ ] Yes
[X ] No
```
=> Data Mapping

bin/migration/README.md, bin/migration/main_script.py, bin/migration/migration_reports/failed_imports_logger.py, bin/migration/migration_reports/logging_config.json, bin/migration/migration_reports/logging_utils.py, bin/migration/migration_reports/migration_tracker.py, bin/migration/migration_reports/sql_queries.py, bin/migration/tables/helpers.py, bin/migration/tables/participants.py
https://tools.hmcts.net/jira/browse/S28-2518 
This PR enhances the logging functionality within the migration process and refactors the logging method to log to a database table instead of a txt file. The key improvements and changes include:
Integration of Logging Configuration: Integrated a logging config file (logging_config.json) to manage logging settings centrally. This configuration allows for easy adjustment of log levels, formatting, and output destinations.
Logging to Database Table: Implemented logging to a database table (failed_imports) to store failed migration logs instead of txt files. This approach offers these benefits:
* Centralised storage of logs within the database, allowing easier access and querying.
* Improved reliability of log data, compared to storing logs in …
=> refactor of migration tracker and migration logger

infrastructure/main.tf, pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/controllers/RoomController.java, src/main/java/uk/gov/hmcts/reform/preapi/services/RoomService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/RoomControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/RoomServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2538
- Add endpoint `GET /rooms` returning all rooms
```
[ ] Yes
[x] No
```
=> S28 2538: Add endpoint GET `/rooms`

infrastructure/main.tf, src/main/java/uk/gov/hmcts/reform/preapi/repositories/RecordingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/ReportService.java, src/test/java/uk/gov/hmcts/reform/preapi/services/ReportServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2317
- Fix error caused by custom query expecting one result but receiving multiple
```
[ ] Yes
[x] No
```
=> S28 2317: Fix Concurrent Capture Sessions Report 500 Error

infrastructure/main.tf, pre-api-stg.yaml, src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/UserServiceIT.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/UserController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchUsers.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/UserRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/UserService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/UserControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/UserServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2264
- Remove search param `firstName`
- Remove search param `lastName`
- Add search param `name`
- Logical change -> firstName AND lastName AND email AND ...  -> (name OR email) AND ...
```
[ ] Yes
[x] No
```
=> S28 2264: GET `/users` Search Param `name`

infrastructure/main.tf, src/main/java/uk/gov/hmcts/reform/preapi/services/UserService.java
- Fix filter boolean expression to stop 404 portal access not found error on put user.   
```
[ ] Yes
[x] No
```
=> Fix: Access Deletion Causing 404

infrastructure/main.tf, pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/controllers/RecordingController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchRecordings.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/RecordingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/RecordingService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/RecordingControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/params/SearchRecordingsTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceTest.java
- Add recording search param `id`
- Add recording search param `startedAt`
- Remove recording search param `scheduledFor`
```
[ ] Yes
[x] No
```
=> Feature: Add Params `id` and `startedAt` + Remove Param `scheduledFor`

bin/migration/tables/audits.py, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/S28-2566
Updating the 'source' field in audits table. 
This field is also removed from the audit_details json.
```
[ ] Yes
[X ] No
```
=> fixing the source field in the audits table

src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/PortalAccessTest.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/CreatePortalAccessDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/PortalAccessDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/entities/PortalAccess.java, src/main/java/uk/gov/hmcts/reform/preapi/enums/AccessStatus.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/PortalAccessRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/InviteService.java, src/main/java/uk/gov/hmcts/reform/preapi/services/PortalAccessService.java, src/main/java/uk/gov/hmcts/reform/preapi/services/UserService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/UserControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/InviteServiceTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/PortalAccessServiceTest.java
- Reflect db change in spring app
- Remove portal access column status
- Add portal access column logged in
- Add portal access column terms accepted at
```
[ ] Yes
[x] No
```
=> Fix: Portal Access JPA Changes

src/main/java/uk/gov/hmcts/reform/preapi/repositories/BookingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/CaptureSessionRepository.java
- Add call to `timezone` function to change timezone for `scheduled_for` value in query to `Europe/London`
- See if solves problem not present locally 
```
[ ] Yes
[x] No
```
=> S28 2511: Change Timezone in Repository Query

infrastructure/main.tf, pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/controllers/BookingController.java
https://tools.hmcts.net/jira/browse/S28-2615
- Add search params `page` and `size` for pagination on endpoint `GET /bookings/{id}/share`
```
[ ] Yes
[x] No
```
=> S28 2615: Add Search Params `page` and `size`

infrastructure/main.tf
=> Bump API version to 48

bin/migration/tables/recordings.py, infrastructure/main.tf
- [ X] commit messages are meaningful and follow good commit message guidelines
- [ X] README and other documentation has been updated / added (if needed)
- [ X] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/S28-2620
Setting parent_recording_ids to None for original version 1 recordings
```
[ ] Yes
[X ] No
```
=> removing parent_recording_ids for version 1 recordings

infrastructure/main.tf, pre-api-stg.yaml, src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/UserAuthenticationServiceIT.java, src/main/java/uk/gov/hmcts/reform/preapi/config/SecurityConfig.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/InviteController.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/PortalAccessRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/ShareBookingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/security/authentication/UserAuthentication.java, src/main/java/uk/gov/hmcts/reform/preapi/security/service/UserAuthenticationService.java, src/main/java/uk/gov/hmcts/reform/preapi/services/InviteService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/InviteControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/util/HelperFactory.java
=> Enable portal to redeem invites

src/main/java/uk/gov/hmcts/reform/preapi/services/ReportService.java, src/test/java/uk/gov/hmcts/reform/preapi/services/ReportServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2369
- Playback report recording data found from audit_details.recording_id
- Playback report user data found from created_by id (searches both users and app_access table)
```
[ ] Yes
[x] No
```
=> S28 2369: Playback Report Get Data From Audit

infrastructure/data.tf, infrastructure/exception-alert.tf, infrastructure/liveness-alert.tf, src/main/resources/application.yaml
=> Add liveness and exception alerts

src/main/java/uk/gov/hmcts/reform/preapi/repositories/BookingRepository.java
https://tools.hmcts.net/jira/browse/S28-2577
- Filter by capture session instead of recording
```
[ ] Yes
[x] No
```
=> S28 2577: Fix `GET /bookings` Search Param `hasRecordings`

infrastructure/main.tf, pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/controllers/InviteController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchInvites.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/PortalAccessRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/InviteService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/InviteControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/InviteServiceTest.java
- Add search param `accessStatus` to `GET /invites`
```
[ ] Yes
[x] No
```
=> Fix: Add `GET /invites` search param `accessStatus`

bin/migration/tables/recordings.py
https://tools.hmcts.net/jira/browse/S28-2625
Adding a check for recording availability in the recordings manager
```
[ ] Yes
[ X] No
```
=> checking for recording availability and failing if null

README.md
Diagram visible here: https://github.com/hmcts/pre-api/blob/readme-update/README.md
```
[x] Yes
[x] No
```
=> Update mermaid diagram in readme

infrastructure/main.tf, pre-api-stg.yaml, src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/AuditServiceIT.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/BookingServiceIT.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/CaseServiceIT.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceIT.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/ReportServiceIT.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/RoomServiceIT.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/UserAuthenticationServiceIT.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/UserServiceIT.java, src/integrationTest/java/uk/gov/hmcts/reform/preapi/utils/IntegrationTestBase.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/RoomController.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchRooms.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/RoomRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/RoomService.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/RoomControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/RoomServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2734
- Add search param `courtId` to `GET /rooms` to only return rooms linked to the specified court
```
[ ] Yes
[x] No
```
=> S28 2734: Search Rooms by Court Id + Refactor IT

src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/AuditControllerFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/CaseControllerFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/security/XUserIdFilterFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/util/FunctionalTestBase.java
=> S28 2354: FT Scenario Delete Case + Refactor FT

bin/migration/tables/courtregions.py, bin/migration/tables/courtrooms.py, bin/migration/tables/courts.py
https://tools.hmcts.net/jira/browse/S28-2734
- Added new court, associated region and associated rooms
```
[ ] Yes
[x] No
```
=> S28 2734: Migration Script Add New Court

src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/AuditControllerFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/CaseControllerFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/UserControllerFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/util/FunctionalTestBase.java
- Scenario: Create User
- https://tools.hmcts.net/jira/browse/S28-2350
- Scenario: Duplicate Email Address 
- https://tools.hmcts.net/jira/browse/S28-2351
- Add FT Scenario: Create/update a user
- Add FT Scenario: Scenario: Duplicate email address
```
[ ] Yes
[x] No
```
=> Functional Tests: Put User

src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/CaptureSessionControllerFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/util/FunctionalTestBase.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/TestingSupportController.java
https://tools.hmcts.net/jira/browse/S28-2363
- Add `DisplayName` to FT for Delete Booking with recording
- Add FT: Delete Capture Session with recording
- Add FT: Delete Capture Session without recording
```
[ ] Yes
[x] No
```
=> Functional Test: Delete Booking/Capture Session with Recording

infrastructure/main.tf, pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/dto/RecordingDTO.java, src/test/java/uk/gov/hmcts/reform/preapi/dto/RecordingDTOTest.java
- Add field `caseId` to `RecordingDTO`
```
[x] Yes - Unlikely to break power apps upon deploy but will require update to connector
[ ] No
```
=> Feature: Add Case Id to `RecordingDTO` 

src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/CaptureSessionControllerFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/util/FunctionalTestBase.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/TestingSupportController.java
https://tools.hmcts.net/jira/browse/S28-2362
- Add FT Scenario: Delete booking
- Add FT Scenario: Delete capture session
```
[ ] Yes
[x] No
```
=> Functional Test: Delete Booking/Capture Session

src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java
Comment out ft that is failing in master - need to investigate
=> Fix: ft failing in master

src/main/java/uk/gov/hmcts/reform/preapi/dto/validators/NotPastDateValidator.java
https://tools.hmcts.net/jira/browse/S28-2788
- Change timestamp to system local date
```
[ ] Yes
[x] No
```
=> S28 2788: Fix: `NotPastDateValidator`

src/main/java/uk/gov/hmcts/reform/preapi/controllers/InviteController.java
https://tools.hmcts.net/jira/browse/S28-2803
- Convert email to lowercase before redeeming invite
=> fix: convert email to lowercase

bin/migration/requirements.txt
=> adding pandas library dependency

.github/PULL_REQUEST_TEMPLATE.md
- S28-2850
- Update PR template with better instructions and visibilty.
- Need to update and create some sub teams on github
=> S28-2850: Update pr template

data-migration.yml
- S28-2863 https://tools.hmcts.net/jira/browse/S28-2863
- Updated the pipeline YAML file to include the Dev environment as an option in the parameters.
=> S28-2863 : Migration Pipeline - add dev env

src/functionalTest/resources/application.properties
- S28-2852
- Change functional test datasource url to test db
=> S28 2852: Fix Functional Test Data in DB

data-migration.yml
- point to api db instead of spike
=> Update data-migration.yml to point to api db

src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/InviteControllerFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/UserControllerFT.java, src/main/java/uk/gov/hmcts/reform/preapi/controllers/InviteController.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/PortalAccessRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/InviteService.java
- Fix: `POST /invites/redeem/{email}` - must be able compare emails case intensively for both request param and value stored in db
- Add FT for `POST /invites/redeem/{email}` being case insensitive
- Add FT for `GET /users/by-email/{email}` being case insensitive
> [!IMPORTANT]
- Ensure coverage is sufficient for automated tests
- Test Case 1:
- User has an email in the database that is not fully lowercase i.e. `Test.User@Hmcts.net` (and has an invite to the portal).
- Running POST `/invites/redeem/{email}` should work for non-matching email- i.e. `test.user@hmcts.net`
- Test Case 2:
- User has an email in the database that is lowercase `test.user@hmcts.net` (and has an …
=> Fix: `POST /invites/redeem/{email}` Case Insensitive

bin/migration/migration_reports/sql_queries.py, bin/migration/tables/capturesessions.py, bin/migration/tables/participants.py, bin/migration/tables/recordings.py
- Adding NULL recording statuses in the SELECT query for capture sessions and recordings and edge cases where this is null
- Changed sql queries for source db count for capture sessions and recordings
- Adding in edge case for failed import related to missing case_id in participants table
- Changed failed_import table name to 'participants' vs 'contacts' for better clarity
=> adding edge cases

bin/migration/tables/recordings.py
created_at variable wasn't properly assigned.
=> fixing stupid mistake

build.gradle, src/test/java/uk/gov/hmcts/reform/preapi/config/JacksonConfigurationTest.java
- Adding test coverage for the Jackson Configuration as it was previously excluded from coverage
=> Coverage for Jackson Config

charts/pre-api/values.stg.template.yaml
=> Fix: Staging to use Test Storage Accounts

src/main/java/uk/gov/hmcts/reform/preapi/media/AzureMediaService.java
Need more clarity on what is going on with AMS especially around Streaming Endpoints
=> Addition AMS Logging

src/main/java/uk/gov/hmcts/reform/preapi/media/AzureMediaService.java
=> Fix: JWT Key Incorrectly Set (AMS)

charts/pre-api/values.stg.template.yaml
- Switch staging to use MK instead of AMS
-
=> Switch Staging (AMS -> MK)

src/main/java/uk/gov/hmcts/reform/preapi/media/MediaKind.java, src/main/java/uk/gov/hmcts/reform/preapi/tasks/CleanupLiveEvents.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/preapi/media/MediaKindTest.java, src/test/java/uk/gov/hmcts/reform/preapi/tasks/CleanupLiveEventsTest.java
- Fixes an issue where db transactions weren't committed to the db until the end of the cron script
- Stops the live event as soon as possible to reduce the size of the asset to be encoded in MK
=> Transaction fix

src/main/java/uk/gov/hmcts/reform/preapi/media/MediaKind.java
- S28-3206
- Change type of live events created from startLiveEvent endpoint. `Standard` -> `PassthroughBasic`
> [!IMPORTANT]
- Start + play live event from CVP. Stop live event. Check output asset is playable.
=> S28 3206: Create live events with type `PassthroughBasic`

charts/pre-api/Chart.yaml
=> Increase helm version

charts/pre-api/Chart.yaml, charts/pre-api/values.yaml, src/main/resources/application.yaml
- S28-3153
- Reads the necessary flow config to KV per env so that emails can be sent when live events end
=> Add config for flow to KV

charts/pre-api/Chart.yaml, charts/pre-api/values.dev.template.yaml, src/main/java/uk/gov/hmcts/reform/preapi/exception/GlobalControllerExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/preapi/media/FeignErrorDecoder.java, src/test/java/uk/gov/hmcts/reform/preapi/media/FeignErrorDecoderTest.java
- S28-3248
- Add mapping of 409 MK error to api conflict exception
- Fix 500 error thrown when MK put streaming locator encounters 409 exception
=> S28 3248: Handle Streaming Locator 409 Error Response

src/main/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionService.java, src/test/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionServiceTest.java
- S28-3384
> [!IMPORTANT]
> This PR requires manual review by QA
- Start a live event via the app
- Observe request in App Insights (Needs to be in staging as we don't capture App Insights data in dev)
=> Remove extra call to load user from db

build.gradle
- This update broke all of our MK dtos since the objects are no longer convertible to json
=> Revert Azure Resource Manager Update

src/main/java/uk/gov/hmcts/reform/preapi/tasks/CleanupLiveEvents.java, src/main/java/uk/gov/hmcts/reform/preapi/tasks/ClosePendingCases.java, src/main/java/uk/gov/hmcts/reform/preapi/tasks/RobotUserTask.java, src/test/java/uk/gov/hmcts/reform/preapi/tasks/ClosePendingCasesTest.java
- S28-3492
- S28-3191
- Fix: Close case cron job now has a created_by audit value
- Fix: Close case cron job no longer fails on java.lang.IllegalArgumentException
- Fix: Close case cron job no longer sends multiple closure emails due to cron job previously failing
=> S28 3492: Cron Job acts as Robot User

charts/pre-api/Chart.yaml, charts/pre-api/values.yaml
- Use kv secret for workflow id: `flow-case-state-notifier-workflow-id`
-
=> Fix: Case Closed Email Flow Add Env Var

build.gradle
=> Revert "fix(deps): update testcontainers-java monorepo to v1.20.4"

charts/pre-api/Chart.yaml
https://tools.hmcts.net/jira/browse/S28-3685
=> Move base charts to OCI

src/functionalTest/java/uk/gov/hmcts/reform/preapi/email/GovNotifyFT.java, src/main/java/uk/gov/hmcts/reform/preapi/email/govnotify/templates/CasePendingClosure.java
- Date format changed to `d MMMM yyyy` for closure date.
=> S28 3319: Change Date Format for Disassociation Emails

src/functionalTest/java/uk/gov/hmcts/reform/preapi/email/GovNotifyFT.java
=> Changed notify from email to fix func tests

src/main/java/uk/gov/hmcts/reform/preapi/services/BookingService.java
- S28-3576
- Fix error from calling method that should be transaction but wasn't in StartLiveEvent cron job
- Error message: `org.hibernate.LazyInitializationException: Could not initialize proxy [uk.gov.hmcts.reform.preapi.entities.Case] - no session`
=> Fix: Start Live Event Transaction Error

build.gradle
Reverts hmcts/pre-api#869
causing errors in prod with GET /bookings and GET /users prepared statements
=> Revert "chore(deps): update plugin org.springframework.boot to v3.4.3"

charts/pre-api/Chart.yaml, charts/pre-api/values.dev.template.yaml, charts/pre-api/values.yaml
https://tools.hmcts.net/jira/browse/S28-3750
-
-
=> increase pod mem to 3GB

charts/pre-api/Chart.yaml, charts/pre-api/values.yaml
=> Remove un needed mem setting Update Chart.yaml

src/main/java/uk/gov/hmcts/reform/preapi/email/govnotify/GovNotify.java, src/main/java/uk/gov/hmcts/reform/preapi/email/govnotify/templates/PortalInvite.java, src/test/java/uk/gov/hmcts/reform/preapi/email/GovNotifyTest.java
- S28-3742
- Adds link to edit request form to the portal invite email template call to Gov Nofity
> [!IMPORTANT]
- Send a portal invite and verify the new attachment is present in the email
=> Add edit request form to portal invite email

README.md, build.gradle
https://tools.hmcts.net/jira/browse/DTSPO-24952
-
-
=> update fortify-client for gradle issues

infrastructure/main.tf, pre-api-stg.yaml, src/main/java/uk/gov/hmcts/reform/preapi/controllers/RoomController.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/CourtDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/CreateCourtDTO.java, src/main/java/uk/gov/hmcts/reform/preapi/dto/RoomDTO.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/CourtControllerTest.java, src/test/java/uk/gov/hmcts/reform/preapi/controller/RoomControllerTest.java
- Reverts the deletions of the endpoint and dto changes
-
=> Revert optimise courts

src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java, src/functionalTest/java/uk/gov/hmcts/reform/preapi/util/FunctionalTestBase.java
=> Revert: optimise courts fix ft 2

src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/BookingServiceIT.java, src/main/java/uk/gov/hmcts/reform/preapi/alerts/SlackMessage.java, src/main/java/uk/gov/hmcts/reform/preapi/alerts/SlackMessageJsonOptions.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/BookingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/BookingService.java, src/main/java/uk/gov/hmcts/reform/preapi/tasks/GetScheduledBookings.java, src/main/java/uk/gov/hmcts/reform/preapi/tasks/StartLiveEvents.java, src/test/java/uk/gov/hmcts/reform/preapi/alerts/SlackMessageTest.java, src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java, src/test/java/uk/gov/hmcts/reform/preapi/tasks/GetScheduledBookingsTest.java, src/test/java/uk/gov/hmcts/reform/preapi/tasks/StartLiveEventsTest.java
https://tools.hmcts.net/jira/browse/S28-3984
Add cron job to post details of today's scheduled bookings to Slack
=> S28-3984 Add GetScheduledBookings job

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/preapi/tasks/AddNROUsersIT.java, src/main/java/uk/gov/hmcts/reform/preapi/Application.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/CaptureSessionRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/repositories/RecordingRepository.java, src/main/java/uk/gov/hmcts/reform/preapi/services/UserService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/preapi/services/UserServiceTest.java
Adds Caffeine caching for loading users by email and id
=> Improve speed of Playback reports and concurrent capture session report

src/main/java/uk/gov/hmcts/reform/preapi/media/MediaKind.java, src/main/java/uk/gov/hmcts/reform/preapi/media/storage/AzureIngestStorageService.java, src/main/java/uk/gov/hmcts/reform/preapi/media/storage/AzureStorageService.java, src/main/java/uk/gov/hmcts/reform/preapi/tasks/CleanupLiveEvents.java, src/main/java/uk/gov/hmcts/reform/preapi/tasks/ProcessCaptureSessions.java, src/test/java/uk/gov/hmcts/reform/preapi/media/MediaKindTest.java, src/test/java/uk/gov/hmcts/reform/preapi/media/storage/AzureIngestStorageServiceTest.java, src/test/java/uk/gov/hmcts/reform/preapi/tasks/CleanupLiveEventsTest.java, src/test/java/uk/gov/hmcts/reform/preapi/tasks/ProcessCaptureSessionsTest.java
This reverts commit 177c0060b2f7bebb17fd9cc5e98b3cc1afd201bd.
-
-
=> Revert "S28 3657: Blob Tagging for Deletion (#910)"

charts/pre-api/Chart.yaml
=> update chart version

charts/pre-api/Chart.yaml
=> Vodafone patch

src/main/java/uk/gov/hmcts/reform/preapi/batch/application/writer/MigrationWriter.java
I'm wondering if we should have kept this in: https://stackoverflow.com/questions/34902380/commit-failed-while-step-execution-data-was-already-updated
=> Reinstate the transactions Propagation new flag
