hmcts/pre-api

- build.gradle
> Downgrade gradle flyway plugin to 9.x due to bug with migrations

- config/owasp/suppressions.xml
- src/test/java/uk/gov/hmcts/reform/preapi/controller/BookingControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/CaseControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/RecordingControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/CaseServiceTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceTest.java
> Revert class name changes which happened during DTO refactor

- src/main/java/uk/gov/hmcts/reform/preapi/controllers/CaseController.java
- Error handling for when PUT `cases/{id}` request body id is null
```
[ ] Yes
[x] No
```
> Fix: 500 Error on PUT `cases/{id}` Request Body id is null

- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/RecordingController.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchRecordings.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/CaptureSessionRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/RecordingRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/RecordingService.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/RecordingControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2290
- Flattened recording endpoints from `/bookings/{bookingId/recordings` -> `/recordings`
- Added pagination to search recordings endpoint (`GET /recordings`)
```
[x] Yes - Endpoints removed but not in prod yet
[ ] No
```
> S28 2290: Flatten Recordings API Endpoints

- pre-api-stg.yaml
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/ReportController.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/reports/EditReportDTO.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/RecordingRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/ReportService.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/ReportControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/ReportServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2367
- Add endpoint `GET /reports/edits` to replace `v_recording_edits_report`
```
[ ] Yes
[x] No
```
> S28 2367: API Report Edits

- pre-api-stg.yaml
- src/main/java/uk/gov/hmcts/reform/preapi/dto/base/BaseRecordingDTO.java
- Changed duration implementation to string instead of the duration object
```
[ ] Yes
[x] No
```
> Fix: `/recordings` Duration Object in Swagger

- pre-api-stg.yaml
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/ReportController.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/reports/AccessRemovedReportDTO.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/ShareBookingRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/ReportService.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/ReportControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/ReportServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2323
- Add endpoint `GET /reports/share-bookings-removed` to replace `v_recording_access_removed_report`
```
[ ] Yes
[x] No
```
> S28 2323: API Reports Recording Access Revoked

- src/main/java/uk/gov/hmcts/reform/preapi/controllers/CaseController.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/CourtController.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/CourtRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/CourtService.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/CourtServiceTest.java
- Fix issue where page data field was not getting the correct data due to custom page implementation for `GET /courts`
- Moved filtering of courts by region name to court repository
```
[ ] Yes
[x] No
```
> Fix: `GET /courts` Pagination Data Issues

- build.gradle
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/CourtController.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/CreateCourtDTO.java
- src/main/java/uk/gov/hmcts/reform/preapi/exception/GlobalControllerExceptionHandler.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/CourtControllerTest.java
https://tools.hmcts.net/jira/browse/S28-2254
- Add check: id, name, court_type, location_code, regions and rooms values are not null
- Add check: regions and rooms lists are not empty
- Add error message for `HttpMessageNotReadableException` which is caused when values don't map correctly (error message returned when invalid enum value are sent). 
```
[ ] Yes
[x] No
```
> Fix: CreateCourtDTO Ensure Valid

- pre-api-stg.yaml
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/ReportController.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/reports/PlaybackReportDTO.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/AuditRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/ReportService.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/ReportControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/ReportServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2395
https://tools.hmcts.net/jira/browse/S28-1637
- Param `source` is no longer required
- Generic playback report `GET /reports/playback`
- PlaybackReportDTO field updates
- Remove `user` (containing users email)
- Add `userEmail`
- Add `userFullName`
```
[ ] Yes
[x] No
```
> S28 2395: General Playback Report `GET /reports/playback`

- pre-api-stg.yaml
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/CaptureSessionController.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionService.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/CaptureSessionControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2402
- Add endpoint `GET /capture-sessions/{id}`
```
[ ] Yes
[x] No
```
> S28 2402: API GET `/capture-sessions/{id}`

- pre-api-stg.yaml
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/CaptureSessionController.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionService.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/CaptureSessionControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2405
- Add endpoint `DELETE /capture-session/{id}`
```
[ ] Yes
[x] No
```
> S28 2405: API DELETE `/capture-session/{id}`

- pre-api-stg.yaml
- src/main/java/uk/gov/hmcts/reform/preapi/config/OpenAPIConfiguration.java
Power Platform custom connectors suddenly need at least 30n characters in their API description so this will save time when updating it.
```
[ ] Yes
[x] No
```
> Provide swagger with longer API description

- pre-api-stg.yaml
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/BookingController.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/CreateShareBookingDTO.java
- src/main/java/uk/gov/hmcts/reform/preapi/security/AuthorisationService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/ShareBookingService.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/BookingControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/security/AuthorisationServiceTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/ShareBookingServiceTest.java
- Update CreateShareBookingDTO to use UUID instead of BaseUserDTO for `sharedWithUser` and `sharedByUser`
- `sharedByUser` can be inferred from the authenticated user if the value is not set in the request
```
[ ] Yes
[x] No
```
> Fix: Sharing a Booking Uses UUID instead of UserDTO + Callable without `sharedBy` set

- src/main/java/uk/gov/hmcts/reform/preapi/config/SecurityConfig.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/AuditRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/ReportService.java
- Add `/errors` to the list of endpoints to avoid authentication checks on to prevent 401 errors when 500 errors should be returned. 
- Fix 500 error when `/reports/playback` encounters a record with no `createdBy` or `tableRecordId` set
- Fix 500 error with JPA query
```
[ ] Yes
[x] No
```
> Fix: 401 Errors Instead of 500 Errors + `/reports/playback` Error 401 Fix

- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java
- src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/CaseServiceIT.java
- src/main/java/uk/gov/hmcts/reform/preapi/exception/GlobalControllerExceptionHandler.java
- src/main/java/uk/gov/hmcts/reform/preapi/exception/RecordingNotDeletedException.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/RecordingRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/BookingService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/CaseService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/CourtService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/InviteService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/RecordingService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/ReportService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/RoleService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/ShareBookingService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/UserService.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/BookingControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/CaptureSessionControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/CaseControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceTest.java
- When deleting case/booking/capture session an error will occur if there is an associated recording that has not been marked as deleted preventing deleting of any associated entities. 
```
[ ] Yes
[x] No
```
> Fix: Cascade Delete Error When Associated Recording Not Deleted

- src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/UserServiceIT.java
- src/main/java/uk/gov/hmcts/reform/preapi/entities/base/CreatedModifiedAtEntity.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/AppAccessRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/PortalAccessRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/UserService.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/UserServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2267
- On create any entity with `modifed_at` field will automatically set the value for `modifed_at` 
- On delete a user, attached app access entities will have `active` set to `false` (as well as `deleted_at` timestamp set)
- On undelete a user, attached app access entities will be undeleted (and `active` set to `true`)
- On undelete a user, attached portal access entities will be undeleted
```
[ ] Yes
[x] No
```
> S28 2267: Delete/Undelete Updates AppAccess Active Value

- infrastructure/main.tf
- pre-api-stg.yaml
- src/integrationTest/java/uk/gov/hmcts/reform/preapi/entities/PortalAccessTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/UserServiceIT.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/CreatePortalAccessDTO.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/CreateUserDTO.java
- src/main/java/uk/gov/hmcts/reform/preapi/entities/PortalAccess.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/PortalAccessRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/PortalAccessService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/UserService.java
- src/main/resources/db/migration/V017__RemovePortalAccessPasswordField.sql
- src/test/java/uk/gov/hmcts/reform/preapi/controller/UserControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/PortalAccessServiceTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/UserServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2266
- Add `portalAccess` field to CreateUserDTO
- Only allow updating existing portal access entities (must invite to create a new portal access
```
[ ] Yes
[x] No
```
> S28 2266: PUT `/users/{id}` Add Portal Access Field

- infrastructure/main.tf
- pre-api-stg.yaml
- src/main/java/uk/gov/hmcts/reform/preapi/dto/CreatePortalAccessDTO.java
- src/main/java/uk/gov/hmcts/reform/preapi/entities/PortalAccess.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/UserControllerTest.java
- Allow portal_access.invited_at to be nullable (matching db)
```
[ ] Yes
[x] No
```
> Fix: Allow invited_at to be nullable

- infrastructure/main.tf
- pre-api-stg.yaml
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/CaptureSessionController.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchCaptureSessions.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/CaptureSessionRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/BookingService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/CaseService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/RecordingService.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/CaptureSessionControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionServiceTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/CaseServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2563
- Add search param `courtId` to `GET /capture-sessions` 
- Remove hard-coded court filter by court for admins on search endpoints of
- Cases
- Bookings
- Capture sessions 
- Recordings
```
[ ] Yes
[x] No
```
> S28 2563: Remove Hard-coded Court Filter (for API use in Admin Section)

- src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchBookings.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchCaptureSessions.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchCases.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchCourts.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchInvites.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchRecordings.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchSharedReport.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchUsers.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/params/SearchBookingsTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/params/SearchCaptureSessionsTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/params/SearchCasesTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/params/SearchCourtsTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/params/SearchInvitesTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/params/SearchRecordingsTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/params/SearchUsersTest.java
https://tools.hmcts.net/jira/browse/S28-2550
- When a string param is empty `""` it is handled like as a `null` value
```
[ ] Yes
[x] No
```
> S28 2550: Fix Empty String Search Params Affecting Responses

- src/main/java/uk/gov/hmcts/reform/preapi/controllers/BookingController.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/CaptureSessionController.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchBookings.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchCaptureSessions.java
https://tools.hmcts.net/jira/browse/S28-2511
- Change search param `scheduledFor` for `GET /bookings` to type `LocalDate`
- Change search param `scheduledFor` for `GET /capture-sessions` to type `LocalDate`
```
[ ] Yes
[x] No
```
> S28 2511: Fix `scheduledFor` Search Param to `LocalDate`

- infrastructure/main.tf
- pre-api-stg.yaml
- src/main/resources/application.yaml
This will allow services authenticated with APIm to call the /health endpoint of the API to include within their own health checks.
```
[ ] Yes
[x] No
```
> Allow calling /health via APIm

- src/main/java/uk/gov/hmcts/reform/preapi/services/AppAccessService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/PortalAccessService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/UserService.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/AppAccessServiceTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/PortalAccessServiceTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/UserServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2592
- Removing app access sets `active = false` as well as `deleted_at` (functionality like normal app access delete)
- Removing portal access set `status = INACTIVE` as well as `deleted_at` (functionality like normal portal access delete)
```
[ ] Yes
[x] No
```
> S28 2592: `PUT /user/{id}` Deletes App/Portal Access Correctly

- src/main/java/uk/gov/hmcts/reform/preapi/repositories/ShareBookingRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/ShareBookingService.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/ShareBookingServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2693
- Throw a 409 conflict error when booking has already been shared with a user (excluding deleted shares)
```
[ ] Yes
[x] No
```
> S28 2693: Throw Conflict Error on Booking Already Shared with User

- src/main/java/uk/gov/hmcts/reform/preapi/controllers/InviteController.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchInvites.java
- Fix issue where `GET /invites` search param `status` was incorrectly mapped with `SearchInvites` class (with param name `accessStatus`
```
[ ] Yes
[x] No
```
> Fix: Invite search by status

- src/main/java/uk/gov/hmcts/reform/preapi/services/AppAccessService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/UserService.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/UserServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2267
- Use PortalAccessService.deleteById and AppAccessService.deleteById to make all deletions of portal_access and app_access entities act the same way. 
```
[ ] Yes
[x] No
```
> S28 2267: Fix Delete User Deletes Portal Access Correctly

- src/main/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionService.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/RecordingService.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceTest.java
https://tools.hmcts.net/jira/browse/S28-2777
- Undeleting recording also undeletes the related capture session
```
[ ] Yes
[x] No
```
> S28 2777: Undeleting Recording also Undeletes Related Capture Session

- src/main/java/uk/gov/hmcts/reform/preapi/dto/validators/NotPastDateValidator.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/BookingControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/dto/validators/NotPastDateValidatorTest.java
https://tools.hmcts.net/jira/browse/S28-2788
- Fix issue highlighted by timezone change
- `NotPastDateValidator` now takes timezone into account
```
[ ] Yes
[x] No
```
> S28 2788: `NotPastDateValidator` Timezone Fix

- src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/ReportServiceIT.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/ReportService.java
- Add check to `GET /reports/playback` to check that `audit_details` has a not null value for `recordingId` before attempting to search by the value.
```
[ ] Yes
[x] No
```
> Fix: `GET /reports/playback` Error In Caused by Malformed `audit_details`

- infrastructure/main.tf
- pre-api-stg.yaml
- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/CaseControllerFT.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/CreateCaseDTO.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/CaseControllerTest.java
https://tools.hmcts.net/jira/browse/S28-2356
https://tools.hmcts.net/jira/browse/S28-2359
https://tools.hmcts.net/jira/browse/S28-2360
- Add not-null check to case reference field on `CreateCaseDTO`
- Add functional tests:
- Remove Case Reference
- Cannot create a case with reference of more than 13 characters
- Cannot create a case with reference of less that 9 characters
- Create a case with a duplicate case reference in the same court
- Create a case with a duplicate case reference in different court
```
[x] Yes - not null check on case reference field for `CreateCaseDTO` could break power apps 
[ ] No
```
> Functional Test: `PUT /cases/{id}` Case Reference Tests

- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java
- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/CaseControllerFT.java
- src/functionalTest/java/uk/gov/hmcts/reform/preapi/util/FunctionalTestBase.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/CreateCaseDTO.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/ParticipantRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/BookingService.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/CaseControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/BookingServiceTest.java
- S28-2889
- Add validation: `PUT /cases/{id}` request body must have at least one witness and one defendant in `participants` list
- Add validation: `PUT /bookings/{id}`- participants must be in the db and be linked to the same case as the booking. 
> [!IMPORTANT]
- Make request to API to create a new case without any participants- see you get a 400 error
- Make request to API to create a new case with one witness- see you get a 400 error
- Make request to API to create a new case with one defendant- see you get a 400 error
- Make request to API to create a new case with one witness and one defendant- see success 201
- Make request to API to create a new booking with …
> S28 2889: Participant Validation on `PUT /cases/{id}` and `PUT /bookings/{id}`

- src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/ReportServiceIT.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/reports/ConcurrentCaptureSessionReportDTO.java
- src/main/java/uk/gov/hmcts/reform/preapi/entities/CaptureSession.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/CaptureSessionRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/RecordingRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/ReportService.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/ReportServiceTest.java
- S28-2901
- S28-2902
- Fix: Decrease time taken to get response from `GET /reports/recordings-per-case`
- Fix: Decrease time taken to get response from `GET /reports/concurrent-capture-sessions`
> [!IMPORTANT]
- Ensure the functionality has been preserved for the newly updated reports 
- `GET /reports/recordings-per-case`
- Reports on the number of recordings per case (per court)
- `GET /reports/concurrent-capture-sessions`
- Reports on the capture sessions that have been started (and/or finished)
> S28 2901: Fix 504 Errors on Reports

- README.md
- build.gradle
- config/owasp/suppressions.xml
- src/integrationTest/resources/application.properties
- src/main/java/uk/gov/hmcts/reform/preapi/config/ContainerImageNameSubstitutor.java
- src/main/resources/testcontainers.properties
- S28-3109
- Workaround for the errors with pull limits from dockerhub
- This PR will get the app to pull the postgres image from the public hmcts ACR instead of directly from dockerhub.
> Use hmcts ACR for postgres testcontainers

- infrastructure/main.tf
- pre-api-stg.yaml
- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/CourtControllerFT.java
- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/UserControllerFT.java
- src/functionalTest/java/uk/gov/hmcts/reform/preapi/util/FunctionalTestBase.java
- src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/UserServiceIT.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/UserController.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchUsers.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/UserRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/UserService.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/UserControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/UserServiceTest.java
- S28-3102
- Add optional search param `appActive` to `GET /users` endpoint. Filters results by `active` status of app access entities
> [!IMPORTANT]
- If you use the `email` search param for all of the tests then you will ensure you only get the user you are testing with (instead of having to search through all results to find your test user). 
- For all of the tests you should be able to use the same user with the following details app accesses:
- App access 1:
- court= court A 
- active = true
- default court = true
- App access 2: 
- court: court b
- active = false
- default court = false
- Test: Search users by appActive=true, should see user
- Test: Search users by …
> S28 3102: `GET /users` Search Param `appActive`

- infrastructure/main.tf
- pre-api-stg.yaml
- src/main/java/uk/gov/hmcts/reform/preapi/dto/base/BaseAppAccessDTO.java
- S28-2271
- Add field `created_at` to all app access response objects
> [!IMPORTANT]
- Create a user with an app access. Get user via get endpoint, see app access object has `created_at` field
> S28-2271: Add `created_at` field to BaseAppAccessDTO

- src/main/java/uk/gov/hmcts/reform/preapi/dto/validators/PortalAppAccessValidator.java
- src/test/java/uk/gov/hmcts/reform/preapi/dto/validators/PortalAppAccessValidatorTest.java
- S28-3114
- Fix 500 error when attempting to create/update an app access with a null value in role_id
> [!IMPORTANT]
- Attempt to create a user with an app_access[].role_id as null. See no 500 error, see 400 error telling you to set the value of role_id to not null value
> S28 3114: Fix 500 Error on `PUT /users/{id}` when `app_access[].role_id` is null

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/preapi/util/FunctionalTestBase.java
- src/main/java/uk/gov/hmcts/reform/preapi/config/JacksonConfiguration.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/AuditControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/BookingControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/CaptureSessionControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/CaseControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/CourtControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/RecordingControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/UserControllerTest.java
- Add deserializer for timestamps (fix parse error for create/update endpoints with timestamp body params)
> Fix: Add deserializer for timestamp (jackson config)

- charts/pre-api/values.dev.template.yaml
- src/main/java/uk/gov/hmcts/reform/preapi/media/AzureMediaService.java
- src/test/java/uk/gov/hmcts/reform/preapi/media/AzureMediaServiceTest.java
- S28-3151
- Add AMS implementation for `/media-service/vod` endpoint
> [!IMPORTANT]
- Look on AMS, see there is NOT a content key policy with a name matching your user id. Call endpoint, see one is created.
- Call endpoint for valid asset, on asset you are trying to watch, see a new locator with a name that matches the user's id.
- See start time is now, end time is one hours time. Call the endpoint again after one minute. See times update.
-  _NOTE: The time displayed on AMS is UTC so times will be -1 hour of actual time_
- Check response works for viewing the asset (see steps below)
- Call endpoint for a recording that the user does not have access to
- Call endpoint for a …
> S28 3151: Asset Playback (AMS Implementation)

- src/main/java/uk/gov/hmcts/reform/preapi/controllers/MediaServiceController.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/MediaServiceControllerTest.java
- Fix: `playLiveEvent` endpoint creates a streaming endpoint and locator when capture session's `status` is `RECORDING` but `liveOutputUrl` is `null`
> Fix: `playLiveEvent` Error When `checkStream` Called First

- src/main/java/uk/gov/hmcts/reform/preapi/media/AzureMediaService.java
- src/main/java/uk/gov/hmcts/reform/preapi/media/MediaKind.java
- S28-3173
- Expire streaming locators for VOD at 1 second before midnight today
> [!IMPORTANT]
- Watch a video on demand longer than an hour and you should still be able to play without your streaming locator expiring.
> Expire streaming locators at midnight today

- src/main/java/uk/gov/hmcts/reform/preapi/media/AzureMediaService.java
- S28-3182
- Fix: locator name on create and delete didn't match so stop live event failed to delete streaming locator (AMS implementation)
-
> [!IMPORTANT]
- Test: streaming locator is deleted on stop live event endpoint called (AMS implementation)
-
> S28 3182: Locator not Deleted on Stop Live Event (AMS Implementation)

- infrastructure/main.tf
- pre-api-stg.yaml
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/MediaServiceController.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/MediaServiceControllerTest.java
- S28-2972
- Update response when capture session is already RECORDING: 204 -> 200 + capture session
- Update response when capture session has been updated to RECORDING: 204 -> 200 + capture session
> S28 2972: Revert Making Check Stream Not Return Capture Session

- src/main/java/uk/gov/hmcts/reform/preapi/dto/media/LiveEventDTO.java
- src/main/java/uk/gov/hmcts/reform/preapi/media/MediaKind.java
- src/main/java/uk/gov/hmcts/reform/preapi/media/dto/MkLiveEventProperties.java
- src/test/java/uk/gov/hmcts/reform/preapi/media/MediaKindTest.java
- S28-3185
- MediaKind live events are created with RTMPS ingest
> [!IMPORTANT]
- Test the returned ingest url returned by endpoints works with MK. 
- Ensure make sure MK ingest url starts with `rtmps://`
> Fix: Enable RTMPS on MK

- src/main/java/uk/gov/hmcts/reform/preapi/controllers/MediaServiceController.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/MediaServiceControllerTest.java
- S28-3171
- Check stream endpoint checks for `gc_state` if cannot find `.ism` file- fix issue where check stream endpoint was not finding a stream
> [!IMPORTANT]
- Start live event, start CVP recording, run check stream and see it finds the stream (status=RECORDING). MK has a slight delay so might have to wait a few seconds
- Start live event, do NOT start CVP recording, run check stream and is it does not find a stream (status=STANDBY)
> S28 3171: Check stream MK not looking for `gc_state`

- src/main/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionService.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionServiceTest.java
- S28-3350
Switch the filename used for capture sessions depending on whether the API is running under AMS or MK
This will need testing in staging so that you can see the change appearing in the App when the edit video button is clicked
> Change the filename used per media service

- src/main/java/uk/gov/hmcts/reform/preapi/tasks/CleanupLiveEvents.java
- src/test/java/uk/gov/hmcts/reform/preapi/tasks/CleanupLiveEventsTest.java
- S28-3259
- Stop live event when capture session does not exist (in non-prod) now stops/deletes live event, live output and locator and no longer runs transforms
> Fix: Stop Live Event Cron Job Null Errors

- src/main/java/uk/gov/hmcts/reform/preapi/controllers/MediaServiceController.java
- S28-3550
- Set the filename in the Recording of the edited file when generating the asset
> [!IMPORTANT]
- Create an edit of a recording and then edit that new recording again
> Save filename of edited recording in the DTO

- src/main/java/uk/gov/hmcts/reform/preapi/media/MediaKind.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionService.java
- src/test/java/uk/gov/hmcts/reform/preapi/media/MediaKindTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/CaptureSessionServiceTest.java
- S28-3259
- Fix issue causing live events with names that cannot be parsed to UUIDs not being cleaned up correctly
- UUID parsing caused an error which meant the API was skipping the cleanup of the live event
- Fix issue causing live events created manually to not get cleaned up
- The naming convention of the live output created when you create a live event via the dashboard is different to the live outputs created via the API so it was not getting caught by the API to delete. This resulted in the call to the MK stop live event API returning a 400 error (making the API skip cleanup).
> S28 3259: Fix Stop Live Event Cron Errors

- src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/UserAuthenticationServiceIT.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/AppAccessRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/security/service/UserAuthenticationService.java
- S28-3458
- Fix issue where app access's with active=False but not deleted is allowing user's access
> [!IMPORTANT]
- Create a user with app access, set the app access to active=False. See can no longer user app access id as X-User-Id
> S28 3458: Disable access for app access when it is active=False

- infrastructure/main.tf
- pre-api-stg.yaml
- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/RecordingControllerFT.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/RecordingDTO.java
- src/main/java/uk/gov/hmcts/reform/preapi/entities/Recording.java
- src/test/java/uk/gov/hmcts/reform/preapi/dto/RecordingDTOTest.java
- S28-3434
- Add RecordingDTO.totalVersionCount which is the count of all versions of a recording (including all edits and the original).
> S28 3434: Add `totalVersionCount` to `RecordingDTO`

- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java
- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/CaptureSessionControllerFT.java
- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/CaseControllerFT.java
- src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/CaseServiceIT.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/CaseService.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/CaseServiceTest.java
- S28-3488
- On case closure: 
- Delete bookings with a capture session in the state `NO_RECORDING` (cascades to delete capture session as well)
- Delete bookings with a capture session in the state `FAILURE` (cascades to delete capture session as well)
> [!IMPORTANT]
- Create a case with three bookings and setup capture sessions using `PUT /capture-sessions/{id}`: 
- One booking/capture session with the status `NO_RECORDING`
- One booking/capture session with the status `FAILURE`
- One booking/capture session with the status `RECORDING_AVAILABLE`
- Mark the case as closed via `PUT /cases/{id}`
- Test 1: 
- `GET /bookings/{id}` for the first booking, see 404 (because booking …
> S28 3488: On Closed Case Delete Bookings w/ Capture Session No Recording or Failure

- infrastructure/main.tf
- pre-api-stg.yaml
- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/BookingControllerFT.java
- src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/BookingServiceIT.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/BookingController.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/BookingRepository.java
- S28-3554
- Add sort param to `GET /bookings` endpoint for sorting bookings response
- This is for ticket sorting requirement: sort by capture session finishedAt desc
> [!IMPORTANT]
- Sort bookings by capture session finishedAt by using param sort: `cs.finishedAt,desc`
- `GET /bookings?sort=cs.finishedAt,desc`
> S28 3554: Bookings Sorting Param

- charts/pre-api/values.dev.template.yaml
- docker-compose.yml
- docker/database/Dockerfile
- docker/database/init-db.sh
- src/main/resources/db/migration/V026__AddNewCourtsNRO.sql
- S28-3615   ( refer to ticket for court info added in this PR + Colin's comments)
- Updated location code for **'Exeter Crown Court'** to `423`.
- Added location code for **'Kingston-upon-Thames Crown Court'** to `427`.
- Added 74 new courts to the `courts` table using generated UUIDs.
- Mapped courts to regions dynamically based on location codes (72 mappings - 2 courts with no location code)
- Implemented audit entries for all new court additions (74 courts).
> S28 3615/new courts nro

- src/main/java/uk/gov/hmcts/reform/preapi/services/ReportService.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/ReportServiceTest.java
- S28-3604
- Reports now accept the audit details recording id key to be called `recordingId` or `recordinguid` to allow for a data discrepancy in audit data received from the App
> [!IMPORTANT]
- Watch recordings build up playback audit
- pull the playback report to see it populated properly
> Accept recordinguid field in audit for reports

- src/main/resources/db/migration/V027__UpdateNewCourtsNRO.sql
- S28-3615   ( refer to ticket for court info added in this PR + Colin's comments)
- Updated name for **'Exeter Crown Court'** to `Exeter Combined Court Centre`.
- Updated name for **'Liverpool Crown Court'** to `Liverpool QEII Law Courts: Liverpool Crown Court`.
- Updated name for **'Mold Crown Court'** to `Mold Justice Centre (Mold Law Courts)`.
- Updated name for **'Nottingham Crown Court'** to `Nottingham County Court & Family Court Crown Court`.
- Updated name for **'Kingston upon Thames Crown Court'** to `Kingston-upon-Thames Crown Court`.
- Added 1 new courts to the `courts` table using generated UUIDs.  This is for **'Birmingham Crown Court & Annex'**
- Mapped new court to region dynamically
- Implemented audit entry for new court addition.
- Implemented audit entries for all …
> SQL to update existing court names and add Birmingham court

- src/main/java/uk/gov/hmcts/reform/preapi/services/InviteService.java
- S28-3316
- Remove check for only sending email on creation of invite service. Now sends email on successful call to user upsert from invite method (`userService.upsert(CreateInviteDTO createInviteDTO)`).
> S28 3316: Trigger Re-Invitation Email for User

- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/OpenAPISpecFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/preapi/util/FunctionalTestBase.java
https://tools.hmcts.net/jira/browse/S28-3377
- Changed functional tests so they always use the app spun up by spring
> S28-3377 Functional test changes

- infrastructure/main.tf
- pre-api-stg.yaml
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/TestingSupportController.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/CaseDTO.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/CreateCaseDTO.java
- src/main/java/uk/gov/hmcts/reform/preapi/entities/Case.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/CaseService.java
- src/main/resources/db/migration/V029__CaseOrigin.sql
- src/test/java/uk/gov/hmcts/reform/preapi/dto/CaseDTOTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/CaseServiceTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/util/HelperFactory.java
- S28-3770
- Add `origin` to cases
> [!IMPORTANT]
- Ensure migration works as expected (all current cases should be set to origin=PRE)
- Ensure PUT /case/{id} works when origin is `null` (to avoid breaking power apps), `PRE` and `VODAFONE`. 
- Ensure GET /cases/{id} returns a case with the field origin
> S28 3770: Add `origin` to Cases

- src/main/java/uk/gov/hmcts/reform/preapi/media/MediaKind.java
- src/test/java/uk/gov/hmcts/reform/preapi/media/MediaKindTest.java
- S28-3773
- Graceful shutdown live event when startLiveEvent's asset creation encounters 409 Conflict.
> Fix: Start Live Event Asset Conflict

- src/main/java/uk/gov/hmcts/reform/preapi/media/MediaKind.java
- src/test/java/uk/gov/hmcts/reform/preapi/media/MediaKindTest.java
- Fix issue causing `PUT /media-service/streaming-locator/live-event/{id}` endpoint to receive 400 from MK on attempting to create a streaming locator that already exists
> [!IMPORTANT]
- `POST /testing-support/create-well-formed-booking` to create the booking
- Create a capture session for the booking via `PUT /capture-session/{id}`
- Call `PUT /media-service/live-event/start/{captureSessionId}` to start the MediaKind live event
- Call `GET /media-service/live-events/{liveEventName}` until status is Running
- Use the live event (CVP or OBS)
- Call `POST /media-service/live-event/check/{id}` until not erroring
- Call `PUT /media-service/streaming-locator/live-event/{id}`
- …
> Fix: Check Streaming Locator Exists Before Attempting Create

- src/main/java/uk/gov/hmcts/reform/preapi/services/ReportService.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/ReportServiceTest.java
- S28-3574
- Add check for created_by matching portal access id if fails match with user id and app access id
> S28 3574: Try Portal Access Id for Playback Report User Created By

- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/CaseControllerFT.java
- src/main/java/uk/gov/hmcts/reform/preapi/security/AuthorisationService.java
- src/test/java/uk/gov/hmcts/reform/preapi/security/AuthorisationServiceTest.java
PR checklist:
- S28-3958
- Allow Level 3&4 users to PUT /cases/<id>, as long as they are creating a case, or pushing a case state of NULL to an OPEN case.
- I've commented out the added Functional Tests, as there is an outstanding issue with how the tests are working in `updateCaseStatusAuthError()`, the current tests are getting 403 to reasons other than the case state.
As Level 3&4:
- Creating case ✅ 
- Updating case state: ❌ 
- Updating OPEN case but not supplying a case state ✅ 
- Updating a non-OPEN case but not supplying a case state ❌
> S28-3958 Fix Level 4 Create Bookings Functionality

- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/MediaServiceControllerFT.java
- src/functionalTest/java/uk/gov/hmcts/reform/preapi/controllers/RecordingControllerFT.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/MediaServiceController.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/RecordingController.java
- S28-3976
- Remove level 4 access from the following endpoints
- GET /recordings
- GET /recordings/{id}
- GET /media-service/vod
> S28 3976: Restrict LEVEL 4 Access to VOD and Recordings

- infrastructure/main.tf
- pre-api-stg.yaml
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/ReportController.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/reports/PlaybackReportArgsRecord.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/reports/PlaybackReportDTOV2.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/reports/UserRecordingPlaybackReportDTOV2.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/ReportService.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/ReportControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/ReportServiceTest.java
- S28-3167
- Split out View Per Media Held Report into separate endpoint and rename to User Recording Playback Report
- New report is the same as the Application and Portal playback reports but without the timezone column...
> Separate out View Per Media Held Report and rename

- src/main/java/uk/gov/hmcts/reform/preapi/tasks/ProcessCaptureSessions.java
- S28-3748
- increase processing job timeout to 2hrs
> fix: extend timeout for processing capture sessions to 2 hours

- src/main/java/uk/gov/hmcts/reform/preapi/controllers/AuditController.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/TestingSupportController.java
- src/main/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchAudits.java
- src/main/java/uk/gov/hmcts/reform/preapi/dto/AuditDTO.java
- src/main/java/uk/gov/hmcts/reform/preapi/repositories/AuditRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/AuditService.java
- src/test/java/uk/gov/hmcts/reform/preapi/controller/AuditControllerTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/controllers/params/SearchAuditsTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/dto/AuditDTOTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/AuditServiceTest.java
- S28-2058
- S28-2059
- Search audits via GET /audits endpoint by:
- `after`- Search by created_at after timestamp provided
- `before`- Search by created_at before timestamp provided
- `functionalArea`
- `source`
- `userName`- Search by associated user's name (first/last/full) via `created_by`
- `courtId`- Search by association to a court
- `caseReference`- Search by association to a case
> S28 2059: Search Audits

- src/main/java/uk/gov/hmcts/reform/preapi/batch/application/services/persistence/InMemoryCacheService.java
- src/test/java/uk/gov/hmcts/reform/preapi/batch/application/services/persistence/InMemoryCacheServiceTest.java
- Removed IllegalArgumentException throws from caching methods.
- Ensures migration continues without crashing on bad cache inputs.
> Refactor InMemoryCacheService to avoid exceptions on invalid inputs

- src/integrationTest/java/uk/gov/hmcts/reform/preapi/services/UserTermsAcceptedServiceIT.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/UserTermsAcceptedService.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/UserTermsAcceptedServiceTest.java
- [S28-4188](https://tools.hmcts.net/jira/browse/S28-4188)
- Adds evicting the users cache when a user accepts the terms and conditions. This is meant to prevent the API returning stale info to the portal that the user hasn't accepted the terms and conditions
- Regression test of seeing a recording in Portal
- Create a new user that has not accepted the terms and conditions for the portal
- Login as that user and assert that user is asked just once to accept the terms and conditions
> S28 4188 - User stuck on Terms and Conditions page loop

- src/main/java/uk/gov/hmcts/reform/preapi/repositories/RecordingRepository.java
- src/main/java/uk/gov/hmcts/reform/preapi/services/RecordingService.java
- src/main/java/uk/gov/hmcts/reform/preapi/tasks/migration/BatchImportMissingMkAssets.java
- src/test/java/uk/gov/hmcts/reform/preapi/services/RecordingServiceTest.java
- src/test/java/uk/gov/hmcts/reform/preapi/tasks/migration/BatchImportMissingMkAssetsTest.java
Previously, the method for fetching Vodafone recordings (findAllOriginVodafone) only selected recordings where the associated capture session had a status of NO_RECORDING.
This caused an issue where subsequent versions of recordings (eg. version 2s or COPYs) were not being picked up once an earlier version (version 1) succeeded - because the capture session status had already been updated to RECORDING_AVAILABLE.
Changes:
- Added a new repository query method findAllOriginVodafoneNoDuration() to fetch all Vodafone recordings where recording duration and deleted_at are null 
- updated service layer to use this new method 
- updated tests
>  Mk Assets - to include Vodafone recordings with null duration (not just NO_RECORDING sessions)
